spring.application.name=apigaragem
# Define cores no terminal
spring.output.ansi.enabled=always
# Define path raiz do endpoint
# http://localhost:8080/apigaragem/algumacoisa
server.servlet.context-path=/apigaragem
spring.profiles.active=test